#!/usr/bin/env -S bash -euE

set -o pipefail

rm dst/*
cp src/style.css dst/style.css

genSidebar() {
  echo '<ul>'

  for f in $(ls src/ | grep '\.md$') ; do
    title="$(cat "src/$f" | head -n 1 | sed 's;^# *;;g')"
    href="$(printf '%s' "/$f" | sed 's;\.md$;.html;g')"
    echo "<li><a href=\"$href\">$title<a></li>"
  done

  echo '</ul>'
}

sidebar="$(genSidebar | tr -d '\n')"

for f in $(ls src/ | grep '\.md$') ; do
    out="$(printf '%s' "$f" | sed 's;\.md$;.html;g')"
    echo "src/$f -> dst/$out"

    article="$(pandoc "src/$f" -o '-')"
    printf '%s' "$article" > "dst/$out"

    pandoc "src/$f" \
      --template template.html \
      -V sidebar="$sidebar" \
      -o "dst/$out"
done

